### PR TITLE
Update numpy version to correct np.float error

### PR DESCRIPTION
**Pull request by arsedler9**
`numpy` 1.20 removed `np.float` functionality (used in `make_tensors.py`) in favor of `float` and now raises an error. Modified setup to use versions <1.20.

### CODE REVIEW

**Comment by felixp8** [comment]
to be honest, I'm not entirely sure that `np.float` check is doing what I wanted it to. Should probably be using `np.issubdtype` and `np.floating` instead. Plus, since Colab now runs Python 3.10 which isn't compatible `numpy` 1.19, I think fixing those lines of code will be a better solution than changing the version requirement. I'll work on putting that together in the next day or so

**Comment by arsedler9** [comment]
Makes sense, I tried just replacing np.float with Python float and that worked too. Might be a bit cleaner.

**Comment by felixp8** [comment]
Yeah I think replacing `np.float` with `float` preserves the current functionality, but what I actually intended for that code to do was allow all float dtypes (`float32`, `float64`, etc.) to pass that check, while I believe using `float` or `np.float` only allows `float64` to pass. Will test out both solutions

**Review by felixp8 — APPROVED** [review]
So as I suspected, the old code wasn't doing what I wanted it to: I intended for it to convert all float dtypes to `float32`, and all int dtypes to `int32`, but it was only converting `float64` to `float32` and `int64` to `int32`. However, fixing that causes file sizes to roughly double since I had been saving spikes as `float16`. As a result, I also added in gzip compression which is supported natively in `h5py`, which keeps the file size quite small. In any case, the `np.float` issue should be resolved

**Pull request merged**
