### PR TITLE
Handling AttributeError in smooth_spk function of NWBDataset

### LINKED ISSUE #15: Facing AttributeError when trying to use `smooth_spk` function
Hi, 

I was trying to use the `smooth_spk` function of NWBDataset and it throws an AttributeError due to updates in scipy. The native installation of nlb_tools installs `scipy=1.13.1`, which is not compatible with the `smooth_spk` function in `nlb_tools.nwb_intreface.NWBDataset`. 

Code to reproduce:
```
dataset = NWBDataset("<dataset_folder>", "*train")
smoothing_param = 50
dataset.smooth_spk(smoothing_param, name=f'smth_{smoothing_param}', ignore_nans=True)
```

Error:
```
AttributeError: module 'scipy.signal' has no attribute 'gaussian'
```

### PR DESCRIPTION
**Pull request by arnaghosh**
Should close #15

### CODE REVIEW

**Comment by arnaghosh** [comment]
Hi @felixp8, 
Could you please review/approve the PR whenever you get time. I am planning on using this library for another project, and it would be nice to use pip install instead of installing from my fork 😅 

Thanks in advance. :)

**Comment by felixp8** [comment]
sorry for the delay! I removed the try-except block since `scipy.signal.windows` has been the recommended way to access the function for a few years now since version 1.1.0, so I just updated the version requirement also. I will try to make the pip release soon

**Review by felixp8 — APPROVED** [review]

**Comment by felixp8** [comment]
new version is uploaded to pypi

**Comment by arnaghosh** [comment]
Thanks a lot Felix. No worries about the delay! :)

**Pull request merged**
