### PR TITLE
NWBDataset: allow nwbfile argument

### PR DESCRIPTION
**Pull request by magland**
This is a simple change to allow the fpath argument in NWBDataset to be an nwbfile object (in addition to a str). This is needed in my use case because the nwb file is not on the local disk, but is loaded remotely. So I need to prepare a special nwbfile object that gets passed in.

This is where I am using it: https://github.com/magland/dendro_analyses/tree/main/apps/cebra1

You can see my Dockerfile right now is pointing to my forked version. If you merge this PR and release a new version to pypi, that will allow me to make a proper pip install in the Dockerfile.

Thanks!

### CODE REVIEW

**Comment by felixp8** [comment]
@magland The changes seem reasonable to me at first glance! I'm quite busy now but I can try to make the PyPI release this weekend.

Worth mentioning though that NWBDataset will not work with the vast majority of datasets on DANDI, since it was designed just for the ones I uploaded. I've been considering (aka procrastinating about) trying to make it more general and possibly supporting lazy reading instead of loading everything into memory. Would that be useful for the CEBRA app? It would take a good bit longer for me to do though.

**Comment by magland** [comment]
Thanks @felixp8 

> Worth mentioning though that NWBDataset will not work with the vast majority of datasets on DANDI, since it was designed just for the ones I uploaded. I've been considering (aka procrastinating about) trying to make it more general and possibly supporting lazy reading instead of loading everything into memory. Would that be useful for the CEBRA app? It would take a good bit longer for me to do though.

I'm happy to help. What are the main obstacles / differences? Do you know of some specific dandiset examples that I can look at?

Tagging @bendichter

**Comment by felixp8** [comment]
I'd need to revisit the code to give specifics (it's been a while), but I believe NWBDataset assumes a lot of things about the input NWBFile that aren't true in general, e.g. that all behavioral data are aligned to each other, just to avoid the additional complexity those things impose. Of course there are also NLB-specific things like held-out units and train/val/test splits that aren't generally applicable either.

Hard to say what I'd need help on before I start working on it but I do think some assistance could eventually be useful :) Is there a deadline you're aiming for with the CEBRA app?

**Comment by magland** [comment]
> Is there a deadline you're aiming for with the CEBRA app?

No particular deadline. Let me know once you decide to start tackling it.

**Comment by felixp8** [comment]
went ahead and merged this, will try to prepare a PyPI release by EOD. Further improvements to NWBDataset mentioned above can be discussed/tracked in #14

**Comment by felixp8** [comment]
@magland pypi release is done, let me know if you run into any issues with it!

**Pull request merged**
